shutdown_costmaps: false
controller_frequency: 10.0
planner_patience: 30.0
controller_patience: 15.0
conservative_reset_dist: 5.0
planner_frequency: 0.02
oscillation_timeout: 10.0
oscillation_distance: 0.2

